package demo.eradardemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditMemo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String third_party_ref;
	private double amount;
	private double supplier_id;
	private java.lang.String supplier_name;
	private double customer_id;
	private java.lang.String customer_name;

	private double cm_id;

	private java.util.Date cm_date;

	private boolean cm_gotoNextRule;

	private boolean cm_null_alert;

	private double cm_hdr_amt;

	private double cm_dtld_amt;

	public CreditMemo() {
	}

	public java.lang.String getThird_party_ref() {
		return this.third_party_ref;
	}

	public void setThird_party_ref(java.lang.String third_party_ref) {
		this.third_party_ref = third_party_ref;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getSupplier_id() {
		return this.supplier_id;
	}

	public void setSupplier_id(double supplier_id) {
		this.supplier_id = supplier_id;
	}

	public java.lang.String getSupplier_name() {
		return this.supplier_name;
	}

	public void setSupplier_name(java.lang.String supplier_name) {
		this.supplier_name = supplier_name;
	}

	public double getCustomer_id() {
		return this.customer_id;
	}

	public void setCustomer_id(double customer_id) {
		this.customer_id = customer_id;
	}

	public java.lang.String getCustomer_name() {
		return this.customer_name;
	}

	public void setCustomer_name(java.lang.String customer_name) {
		this.customer_name = customer_name;
	}

	public double getCm_id() {
		return this.cm_id;
	}

	public void setCm_id(double cm_id) {
		this.cm_id = cm_id;
	}

	public java.util.Date getCm_date() {
		return this.cm_date;
	}

	public void setCm_date(java.util.Date cm_date) {
		this.cm_date = cm_date;
	}

	public boolean isCm_gotoNextRule() {
		return this.cm_gotoNextRule;
	}

	public void setCm_gotoNextRule(boolean cm_gotoNextRule) {
		this.cm_gotoNextRule = cm_gotoNextRule;
	}

	public boolean isCm_null_alert() {
		return this.cm_null_alert;
	}

	public void setCm_null_alert(boolean cm_null_alert) {
		this.cm_null_alert = cm_null_alert;
	}

	public double getCm_hdr_amt() {
		return this.cm_hdr_amt;
	}

	public void setCm_hdr_amt(double cm_hdr_amt) {
		this.cm_hdr_amt = cm_hdr_amt;
	}

	public double getCm_dtld_amt() {
		return this.cm_dtld_amt;
	}

	public void setCm_dtld_amt(double cm_dtld_amt) {
		this.cm_dtld_amt = cm_dtld_amt;
	}

	public CreditMemo(java.lang.String third_party_ref, double amount,
			double supplier_id, java.lang.String supplier_name,
			double customer_id, java.lang.String customer_name, double cm_id,
			java.util.Date cm_date, boolean cm_gotoNextRule,
			boolean cm_null_alert, double cm_hdr_amt, double cm_dtld_amt) {
		this.third_party_ref = third_party_ref;
		this.amount = amount;
		this.supplier_id = supplier_id;
		this.supplier_name = supplier_name;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		this.cm_id = cm_id;
		this.cm_date = cm_date;
		this.cm_gotoNextRule = cm_gotoNextRule;
		this.cm_null_alert = cm_null_alert;
		this.cm_hdr_amt = cm_hdr_amt;
		this.cm_dtld_amt = cm_dtld_amt;
	}

}