package demo.eradardemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DebitMemo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double dm_id;
	private java.lang.String third_party_ref;
	private double amount;
	private java.util.Date dm_date;
	private double supplier_id;
	private java.lang.String supplier_name;
	private double customer_id;
	private java.lang.String customer_name;

	private double dm_hdr_amt;

	private double dm_dtld_amt;

	private double RTV;

	private boolean dm_null_alert;

	private boolean rtv_zero_alert;

	private boolean dm_gotoNextRule;

	public DebitMemo() {
	}

	public double getDm_id() {
		return this.dm_id;
	}

	public void setDm_id(double dm_id) {
		this.dm_id = dm_id;
	}

	public java.lang.String getThird_party_ref() {
		return this.third_party_ref;
	}

	public void setThird_party_ref(java.lang.String third_party_ref) {
		this.third_party_ref = third_party_ref;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public java.util.Date getDm_date() {
		return this.dm_date;
	}

	public void setDm_date(java.util.Date dm_date) {
		this.dm_date = dm_date;
	}

	public double getSupplier_id() {
		return this.supplier_id;
	}

	public void setSupplier_id(double supplier_id) {
		this.supplier_id = supplier_id;
	}

	public java.lang.String getSupplier_name() {
		return this.supplier_name;
	}

	public void setSupplier_name(java.lang.String supplier_name) {
		this.supplier_name = supplier_name;
	}

	public double getCustomer_id() {
		return this.customer_id;
	}

	public void setCustomer_id(double customer_id) {
		this.customer_id = customer_id;
	}

	public java.lang.String getCustomer_name() {
		return this.customer_name;
	}

	public void setCustomer_name(java.lang.String customer_name) {
		this.customer_name = customer_name;
	}

	public double getDm_hdr_amt() {
		return this.dm_hdr_amt;
	}

	public void setDm_hdr_amt(double dm_hdr_amt) {
		this.dm_hdr_amt = dm_hdr_amt;
	}

	public double getDm_dtld_amt() {
		return this.dm_dtld_amt;
	}

	public void setDm_dtld_amt(double dm_dtld_amt) {
		this.dm_dtld_amt = dm_dtld_amt;
	}

	public double getRTV() {
		return this.RTV;
	}

	public void setRTV(double RTV) {
		this.RTV = RTV;
	}

	public boolean isDm_null_alert() {
		return this.dm_null_alert;
	}

	public void setDm_null_alert(boolean dm_null_alert) {
		this.dm_null_alert = dm_null_alert;
	}

	public boolean isRtv_zero_alert() {
		return this.rtv_zero_alert;
	}

	public void setRtv_zero_alert(boolean rtv_zero_alert) {
		this.rtv_zero_alert = rtv_zero_alert;
	}

	public boolean isDm_gotoNextRule() {
		return this.dm_gotoNextRule;
	}

	public void setDm_gotoNextRule(boolean dm_gotoNextRule) {
		this.dm_gotoNextRule = dm_gotoNextRule;
	}

	public DebitMemo(double dm_id, java.lang.String third_party_ref,
			double amount, java.util.Date dm_date, double supplier_id,
			java.lang.String supplier_name, double customer_id,
			java.lang.String customer_name, double dm_hdr_amt,
			double dm_dtld_amt, double RTV, boolean dm_null_alert,
			boolean rtv_zero_alert, boolean dm_gotoNextRule) {
		this.dm_id = dm_id;
		this.third_party_ref = third_party_ref;
		this.amount = amount;
		this.dm_date = dm_date;
		this.supplier_id = supplier_id;
		this.supplier_name = supplier_name;
		this.customer_id = customer_id;
		this.customer_name = customer_name;
		this.dm_hdr_amt = dm_hdr_amt;
		this.dm_dtld_amt = dm_dtld_amt;
		this.RTV = RTV;
		this.dm_null_alert = dm_null_alert;
		this.rtv_zero_alert = rtv_zero_alert;
		this.dm_gotoNextRule = dm_gotoNextRule;
	}

}