package demo.eradardemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SPF implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double spf_id;
	private double amount;

	private java.lang.Double spf_dm_id;

	private java.lang.Double spf_cm_id;

	private java.lang.String dm_lot_num;

	private java.lang.String cm_lot_num;

	private java.lang.Long dm_item_num;

	private java.lang.Long cm_item_num;

	private java.lang.Double WPRI;

	private java.lang.Double WSHG;

	private java.lang.String dm_status;

	private boolean dm_id_null_alert;

	private boolean cm_id_null_alert;

	public SPF() {
	}

	public double getSpf_id() {
		return this.spf_id;
	}

	public void setSpf_id(double spf_id) {
		this.spf_id = spf_id;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public java.lang.Double getSpf_dm_id() {
		return this.spf_dm_id;
	}

	public void setSpf_dm_id(java.lang.Double spf_dm_id) {
		this.spf_dm_id = spf_dm_id;
	}

	public java.lang.Double getSpf_cm_id() {
		return this.spf_cm_id;
	}

	public void setSpf_cm_id(java.lang.Double spf_cm_id) {
		this.spf_cm_id = spf_cm_id;
	}

	public java.lang.String getDm_lot_num() {
		return this.dm_lot_num;
	}

	public void setDm_lot_num(java.lang.String dm_lot_num) {
		this.dm_lot_num = dm_lot_num;
	}

	public java.lang.String getCm_lot_num() {
		return this.cm_lot_num;
	}

	public void setCm_lot_num(java.lang.String cm_lot_num) {
		this.cm_lot_num = cm_lot_num;
	}

	public java.lang.Long getDm_item_num() {
		return this.dm_item_num;
	}

	public void setDm_item_num(java.lang.Long dm_item_num) {
		this.dm_item_num = dm_item_num;
	}

	public java.lang.Long getCm_item_num() {
		return this.cm_item_num;
	}

	public void setCm_item_num(java.lang.Long cm_item_num) {
		this.cm_item_num = cm_item_num;
	}

	public java.lang.Double getWPRI() {
		return this.WPRI;
	}

	public void setWPRI(java.lang.Double WPRI) {
		this.WPRI = WPRI;
	}

	public java.lang.Double getWSHG() {
		return this.WSHG;
	}

	public void setWSHG(java.lang.Double WSHG) {
		this.WSHG = WSHG;
	}

	public java.lang.String getDm_status() {
		return this.dm_status;
	}

	public void setDm_status(java.lang.String dm_status) {
		this.dm_status = dm_status;
	}

	public boolean isDm_id_null_alert() {
		return this.dm_id_null_alert;
	}

	public void setDm_id_null_alert(boolean dm_id_null_alert) {
		this.dm_id_null_alert = dm_id_null_alert;
	}

	public boolean isCm_id_null_alert() {
		return this.cm_id_null_alert;
	}

	public void setCm_id_null_alert(boolean cm_id_null_alert) {
		this.cm_id_null_alert = cm_id_null_alert;
	}

	public SPF(double spf_id, double amount, java.lang.Double spf_dm_id,
			java.lang.Double spf_cm_id, java.lang.String dm_lot_num,
			java.lang.String cm_lot_num, java.lang.Long dm_item_num,
			java.lang.Long cm_item_num, java.lang.Double WPRI,
			java.lang.Double WSHG, java.lang.String dm_status,
			boolean dm_id_null_alert, boolean cm_id_null_alert) {
		this.spf_id = spf_id;
		this.amount = amount;
		this.spf_dm_id = spf_dm_id;
		this.spf_cm_id = spf_cm_id;
		this.dm_lot_num = dm_lot_num;
		this.cm_lot_num = cm_lot_num;
		this.dm_item_num = dm_item_num;
		this.cm_item_num = cm_item_num;
		this.WPRI = WPRI;
		this.WSHG = WSHG;
		this.dm_status = dm_status;
		this.dm_id_null_alert = dm_id_null_alert;
		this.cm_id_null_alert = cm_id_null_alert;
	}

}